### ISSUE TITLE
Add support for relabeled "Kiprim" devices

### ISSUE THREAD

**Issue by MGehrmann** [robbederks/owon-psu-control#1]
Amazon sells the relabeled devices under the Kiprim brand name. There is the DC310S and DC605S. These support the same instruction set as the OWON PSU.

Here is the output on the command "*idn?" -> "KIPRIM,DC310S,22471238,FV:V4.0.0␍␊"

If it is desired, I can make the change and at least test it on a DC310S.

With kind regards

**Comment by robbederks** [comment]
Yes, please feel free to open a (tested) PR!

**Comment by robbederks** [comment]
If this works (which I'm sure it will), maybe I should rename this repo and pip package to something more generic, any suggestions?

**Comment by MGehrmann** [comment]
That's a good idea. Unfortunately, I have no clue for a good catchy name. 
Maybe something with "simple", " low budget" or "basic". But I don't really like all that. 

On the other hand, it is the command set of the OWON devices. And anyone looking for the control of KIPRIN will come across to OWON.

**Comment by robbederks** [comment]
Ok, let's keep it as owon for now! Feel free to open a PR for support once you're ready.

**Comment by robbederks** [comment]
See #2
