### ISSUE TITLE
add more settings

### ISSUE THREAD

**Issue by badsmoke** [robbederks/owon-psu-control#3]
hey cool python module, i am currently building an api and ui for it.

unfortunately i still have a few settings missing, for example reading the actual voltage limit and current limit, as well as set voltage/current values.

also, according to the manual, my power supply offers some functions to set voltage curves. my power supply is the "KIPRIM,DC310S".

thanks for your help

**Comment by robbederks** [comment]
Thanks! Feel free to open a PR with extra functionality, shouldn't be hard to add!

**Comment by badsmoke** [comment]
ok too bad, the documentation does not give more.

the support also does not answer.

**Comment by badsmoke** [comment]
this repo made it easy to add the missing comamands

https://github.com/maximweb/kiprim-dc310s

have sent you a pull request
